# Generated by Django 4.0.4 on 2022-05-17 15:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_model',
            fields=[
                ('account', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for account', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('B', 'Business'), ('P', 'Personal')], default='Personal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for user account', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('account', models.ManyToManyField(to='webapp.account_model')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_model',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, help_text='Tracking Number', primary_key=True, serialize=False)),
                ('delivered', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('P', 'Ready For Pickup'), ('S', 'Sorting'), ('IT', 'In Transit'), ('OD', 'Out For Delivery'), ('D', 'Delivered')], default='Ready For Pickup', max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.account_model')),
            ],
        ),
    ]
