# Generated by Django 4.0.4 on 2022-05-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_model',
            name='company',
            field=models.CharField(default='Uncle Jims Worm Farm', max_length=20),
            preserve_default=False,
        ),
    ]
